name: DevSkim_VisualStudio_Release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: Data/OSS-Tools-Pipeline-Templates
      ref: refs/tags/v2.0.4
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceRepositoriesToScan:
        exclude:
          - repository: 1esPipelines
          - repository: templates
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    stages:
    - stage: Build
      dependsOn: []
      jobs:
      - template: dotnet-build-job.yml@templates
        parameters:
          buildTool: 'msbuild'
          buildConfiguration: 'Release'
          dotnetVersion: '8.0.x'
          targetFramework: 'net47'
          projectPath: 'DevSkim-DotNet/Microsoft.DevSkim.VisualStudio/Microsoft.DevSkim.VisualStudio.csproj'
          projectName: 'DevSkim_VS'
          poolName: MSSecurity-1ES-Build-Agents-Pool
          poolImage: MSSecurity-1ES-Windows-2022
          poolOs: windows
          artifactName: 'vs-archive'
          extraArtifactName: 'Unsigned_Extension'
          extraArtifactLocation: 'extension'
          includeNuGetOrg: false
          nugetFeedsToUse: 'config'
          nugetConfigPath: 'nuget.release.config'
          onInit:
            - task: NuGetAuthenticate@1
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
          - task: UseDotNet@2
            displayName: Install Dotnet 9 SDK
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
          onEnd:
          - task: PowerShell@2
            displayName: Mkdir for Extension
            inputs:
              targetType: 'inline'
              script: mkdir extension
              workingDirectory: '$(Build.StagingDirectory)'
          - task: PowerShell@2
            displayName: Move Extension File
            inputs:
              targetType: 'inline'
              script: 'mv $env:BUILD_STAGINGDIRECTORY/bin/dotnetapp/DevSkim_VS_dotnetapp_$(ReleaseVersion)/*.vsix $env:BUILD_STAGINGDIRECTORY/extension'

    - stage: Release
      dependsOn:
      - Build
      condition: succeeded()
      jobs:
      - job: sign_hash_release
        displayName: Code Sign, Generate Hashes, Publish Public Release
        templateContext:
          outputs:
          - output: pipelineArtifact
            path: '$(Build.StagingDirectory)'
            artifact: 'Signed_Binaries'
        steps:
        - template: nbgv-set-version-steps.yml@templates
        # set-version-steps only sets it for current job, while adding isOutput only sets it for future jobs
        # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=powershell#set-an-output-variable-for-use-in-future-jobs
        - powershell: |
              $version = (nbgv get-version -v AssemblyInformationalVersion).split('+')[0]
              Write-Host "##vso[task.setvariable variable=releaseVersion;isOutput=true]$version"
          name: outputReleaseVersionVar
        - task: DownloadPipelineArtifact@2
          displayName: Retrieve Unsigned Artifact 
          inputs:
            buildType: 'current'
            artifactName: 'Unsigned_Extension'
            targetPath: '$(Build.BinariesDirectory)\Unsigned_Extension'
        - task: AntiMalware@3
          displayName: Anti-Malware Scan
          inputs:
            InputType: 'Basic'
            ScanType: 'CustomScan'
            FileDirPath: '$(Build.BinariesDirectory)'
            EnableServices: true
            SupportLogOnError: false
            TreatSignatureUpdateFailureAs: 'Warning'
            SignatureFreshness: 'UpToDate'
            TreatStaleSignatureAs: 'Warning'
        - task: EsrpCodeSigning@5
          displayName: Code Sign VS Extension
          inputs:
            ConnectedServiceName: 'oss-esrp-signing-v5-connection'
            AppRegistrationClientId: '8694c10c-c89d-4231-9dca-36cb80737ad0'
            AppRegistrationTenantId: '33e01921-4d64-4f8c-a055-5bdaffd5e33d'
            AuthAKVName: 'oss-signing-vault'
            AuthCertName: 'oss-esrp-auth-cert'
            AuthSignCertName: 'oss-esrp-signing-cert'
            FolderPath: '$(Build.BinariesDirectory)\Unsigned_Extension'
            Pattern: '*.vsix'
            signConfigType: 'inlineSignParams'
            inlineOperation: |
              [
                      {
                          "KeyCode" : "CP-233016",
                          "OperationCode" : "OpcSign",
                          "Parameters" : {
                              "FileDigest" : "/fd SHA256"
                          },
                          "ToolName" : "sign",
                          "ToolVersion" : "1.0"
                      },
                      {
                          "KeyCode" : "CP-233016",
                          "OperationCode" : "OpcVerify",
                          "Parameters" : {},
                          "ToolName" : "sign",
                          "ToolVersion" : "1.0"
                      }
                  ]
            SessionTimeout: '60'
            MaxConcurrency: '50'
            MaxRetryAttempts: '5'
        - powershell: 'Get-ChildItem -Path ''$(Build.BinariesDirectory)'' -Recurse CodeSign* | foreach { Remove-Item -Path $_.FullName }'
          displayName: 'Delete Code Sign Summaries'
        - task: PowerShell@2
          displayName: Move Extension File
          inputs:
            targetType: 'inline'
            script: 'mv $env:BUILD_BINARIESDIRECTORY/Unsigned_Extension/*.vsix $env:BUILD_STAGINGDIRECTORY/'
        - task: PowerShell@2
          displayName: Generate Hashes
          inputs:
            targetType: 'inline'
            script: |
              Get-ChildItem $(Build.StagingDirectory) | Foreach-Object {
                $name = $_.Name
                $tmp = (Get-FileHash "$(Build.StagingDirectory)\$name").Hash
                Add-Content $(Build.StagingDirectory)\HASHES.txt "$tmp`t$name"
              }
        - task: PowerShell@2
          displayName: Move VS Marketplace Manifest
          inputs:
            targetType: 'inline'
            script: 'mv $env:BUILD_SOURCESDIRECTORY/DevSkim-DotNet/Microsoft.DevSkim.VisualStudio/publish.manifest.json $env:BUILD_STAGINGDIRECTORY/'
        - task: PowerShell@2
          displayName: Move Readme-gallery.md
          inputs:
            targetType: 'inline'
            script: 'mv $env:BUILD_SOURCESDIRECTORY/DevSkim-DotNet/Microsoft.DevSkim.VisualStudio/Content/readme-gallery.md $env:BUILD_STAGINGDIRECTORY/'

        - task: AzureCLI@2
          displayName: 'Publishing with Managed Identity'  
          inputs:
            azureSubscription: oss-vs-marketplace-publish-mi-connection
            scriptType: "pscore"
            scriptLocation: 'inlineScript'
            inlineScript: |
              $aadToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
              Install-Module VSSetup -Force
              $vsixPublisher = Join-Path -Path (Get-VSSetupInstance -All | Select-VSSetupInstance -Latest).installationPath -ChildPath "VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe" -Resolve
              $vsixPath = Resolve-Path $env:BUILD_STAGINGDIRECTORY\*.vsix -Relative
              & $vsixPublisher publish -payload $vsixPath -publishManifest $(Build.StagingDirectory)/publish.manifest.json -personalAccessToken $aadToken -ignoreWarnings "VSIXValidatorWarning01,VSIXValidatorWarning02,VSIXValidatorWarning08"
            workingDirectory: '$(Build.StagingDirectory)'
      - job: gitHubReleaseJob
        # Based on Documentation: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/releasepipelines/releaseworkflows/releasejob?tabs=standardreleasejob
        displayName: GitHub Release Job
        dependsOn: sign_hash_release
        variables:
          ReleaseVersion: $[ dependencies.sign_hash_release.outputs['outputReleaseVersionVar.releaseVersion'] ]
        # pool: you can optionally specify pool as you would normally do for a standard job
        templateContext:
          type: releaseJob  # Required, this indicates this job is a release job
          isProduction: true  # Required, must be 'true' or 'false'
          inputs:  # All input build artifacts must be declared here
          - input: pipelineArtifact  # Required, type of the input artifact
            artifactName: Signed_Binaries  # Required, name of the pipeline artifact
            targetPath: $(Pipeline.Workspace)/drop  # Optional, specifies where the artifact is downloaded
        steps:
        - task: GitHubRelease@1
          displayName: Release to GitHub
          inputs:
            gitHubConnection: 'github.com_gfs'
            repositoryName: 'microsoft/DevSkim'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'userSpecifiedTag'
            tag: 'VS_v$(ReleaseVersion)'
            title: 'DevSkim VS Extension v$(ReleaseVersion)'
            assets: |
              $(Build.StagingDirectory)/*.vsix
            changeLogCompareToRelease: 'lastNonDraftRelease'
            changeLogType: 'commitBased'