# Azure Pipelines
# https://aka.ms/yaml

name: DevSkim_VSCode_Debug_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - Pipelines/devskim-vscode-debug.yml
    - DevSkim-VSCode-Plugin/*
    - rules/*

resources:
  repositories:
    - repository: templates
      type: git
      name: SecurityEngineering/OSS-Tools-Pipeline-Templates

stages:
- stage: SDL
  jobs:
  - template: sdl-job.yml@templates
    parameters:
      serviceTreeID: '9792b8d3-bc2c-432c-8fc9-bdb143552208'

- stage: Build
  dependsOn: []
  jobs:
  - job: build_vscode_plugin
    displayName: Build VS Code Plugin
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: CodeQL3000Init@0
    - task: Npm@1
      displayName: npm install
      inputs:
        command: 'install'
        workingDir: 'DevSkim-VSCode-Plugin/'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'DevSkim-VSCode-Plugin/'
        customCommand: 'run pack-ext'
    - task: CodeQL3000Finalize@0
    - task: AntiMalware@3
      displayName: Anti-Malware Scan
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: 'DevSkim-VSCode-Plugin/'
        EnableServices: true
        SupportLogOnError: false
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Warning'
    - task: PowerShell@2
      displayName: Move Plugin File
      inputs:
        targetType: 'inline'
        script: 'mv DevSkim-VSCode-Plugin/*.vsix $env:BUILD_STAGINGDIRECTORY'
    - task: PublishBuildArtifacts@1
      displayName: Publish Unsigned Artifact
      inputs:
        PathtoPublish: '$(Build.StagingDirectory)'
        ArtifactName: 'Unsigned_Plugin'
        publishLocation: 'Container'
    - task: PowerShell@2
      displayName: Mkdir for Manifests
      inputs:
        targetType: 'inline'
        script: mkdir sbom/vscode/
        workingDirectory: '$(Build.StagingDirectory)'
    # - task: ManifestGeneratorTask@0
    #   displayName: Generate VS Code Plugin Manifest
    #   inputs:
    #     BuildDropPath: '$(Build.StagingDirectory)/bin/fixme/'
    #     ManifestDirPath: '$(Build.StagingDirectory)/sbom/vscode/'
    #     PackageName: 'DevSkim VS Code Plugin'
    #     PackageVersion: '$(ReleaseVersion)'
    # - task: ArchiveFiles@2
    #   displayName: Archive Manifests
    #   inputs:
    #     rootFolderOrFile: '$(Build.StagingDirectory)/sbom/'
    #     includeRootFolder: false
    #     archiveType: 'zip'
    #     archiveFile: '$(Build.StagingDirectory)/Manifests/DevSkim_VSCode_Manifests.zip'
    #     replaceExistingArchive: true
    # - task: PublishBuildArtifacts@1
    #   displayName: Pipeline Publish Manifest Archive
    #   inputs:
    #     PathtoPublish: '$(Build.StagingDirectory)/Manifests'
    #     ArtifactName: 'Manifests'