# Azure Pipelines
# https://aka.ms/yaml

name: DevSkim_VisualStudio_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - DevSkim-DotNet/Microsoft.DevSkim/*
    - DevSkim-DotNet/Microsoft.DevSkim.VSExtension/*

stages:
- stage: Publish
  jobs:
  - job: publish
    displayName: Publish Visual Studio Extension
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.100'
    - task: NuGetCommand@2
      displayName: NuGet Restore
      inputs:
        command: 'restore'
        restoreSolution: '$(SolutionDirectory)'
        feedsToUse: 'select'
        vstsFeed: '73b0a75c-d420-4e77-95db-e81276361e42'
    - task: MSBuild@1
      inputs:
        solution: '$(SolutionDirectory)/Microsoft.DevSkim.VSExtension'
        msbuildArguments: '/p:Configuration=$(BuildConfiguration) /p:OutputPath=$(Build.BinariesDirectory)/visualstudio/DevSkim_$(ReleaseVersion) /p:DebugType=None'
    - task: AntiMalware@3
      displayName: Anti-Malware Scan
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: '$(Build.BinariesDirectory)'
        EnableServices: true
        SupportLogOnError: false
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Error'
    - task: EsrpCodeSigning@1
      displayName: Code Sign
      enabled: false
      inputs:
        ConnectedServiceName: ''
        FolderPath: '$(Build.BinariesDirectory)\visualstudio\DevSkim_$(ReleaseVersion)'
        Pattern: '*.vsix'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [ ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'
    - powershell: 'Get-ChildItem -Path ''$(Build.BinariesDirectory)'' -Recurse CodeSign* | foreach { Remove-Item -Path $_.FullName }'
      displayName: 'Delete Code Sign Summaries'
    - task: PowerShell@2
      displayName: Move Extension File
      inputs:
        targetType: 'inline'
        script: 'mv $env:BUILD_BINARIESDIRECTORY/visualstudio/DevSkim_$(ReleaseVersion)/*.vsix $env:BUILD_STAGINGDIRECTORY'
    - task: PowerShell@2
      displayName: Generate Hashes
      inputs:
        targetType: 'inline'
        script: |
          Get-ChildItem $(Build.StagingDirectory) | Foreach-Object {
            $name = $_.Name
            $tmp = (Get-FileHash "$(Build.StagingDirectory)\$name").Hash
            Add-Content $(Build.StagingDirectory)\HASHES.txt "$tmp`t$name"
          }
    - task: PublishPipelineArtifact@1
      displayName: Publish All Artifacts
      inputs:
        targetPath: '$(Build.StagingDirectory)'
        artifact: 'Binaries'


  - job: sdl
    displayName: SDL Tools
    dependsOn: publish
    condition: and(succeeded(), eq(variables['RunSDL'], 'TRUE'))
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: MSBuild@1
      displayName: Build Extension
      inputs:
        solution: '$(SolutionDirectory)/Microsoft.DevSkim.VSExtension'
        msbuildArguments: '/p:Configuration=$(BuildConfiguration) /p:OutputPath=$(Build.StagingDirectory) /p:DebugType=Full'
    - task: AntiMalware@3
      displayName: Anti-Malware Scan
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: '$(Build.StagingDirectory)'
        EnableServices: true
        SupportLogOnError: false
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Error'
    - task: ComponentGovernanceComponentDetection@0
      displayName: Component Governance
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'Low'
    - task: notice@0
      displayName: Notice File Generator
      inputs:
        outputformat: 'text'
      continueOnError: true
    - task: PoliCheck@1
      displayName: PoliCheck
      inputs:
        inputType: 'Basic'
        targetType: 'F'
        targetArgument: '$(SolutionDirectory)'
        result: 'PoliCheck.xml'
    - task: BinSkim@3
      displayName: BinSkim
      inputs:
        InputType: 'CommandLine'
      continueOnError: true
    - task: Semmle@0
      displayName: Semmle Scan
      inputs:
        sourceCodeDirectory: '$(SolutionDirectory)'
        language: 'csharp'
        cleanupBuildCommands: 'msbuild Microsoft.DevSkim.VSExtension /p:Configuration=$(BuildConfiguration) /t:Clean'
        buildCommands: 'msbuild Microsoft.DevSkim.VSExtension /p:Configuration=$(BuildConfiguration) /p:DebugType=Full'
        querySuite: 'Recommended'
        timeout: '1800'
        ram: '16384'
        addProjectDirToScanningExclusionList: true
      continueOnError: true
    - task: PublishPipelineArtifact@1
      displayName: Publish PoliCheck Result
      inputs:
        targetPath: '$(Pipeline.Workspace)\_sdt\logs\PoliCheck\PoliCheck.xml'
        artifact: 'PoliCheck.xml'
    - task: PublishPipelineArtifact@1
      displayName: Publish BinSkim Result
      inputs:
        targetPath: '$(Pipeline.Workspace)\_sdt\logs\BinSkim\BinSkim.sarif'
        artifact: 'BinSkim.sarif'
      continueOnError: true
    - task: PublishPipelineArtifact@1
      displayName: Publish Semmle Result
      inputs:
        targetPath: '$(Pipeline.Workspace)\_sdt\logs\Semmle\csharp\Microsoft.DevSkim.VSExtension-csharp-1.sarif'
        artifact: 'Semmle.sarif'
      continueOnError: true