//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevSkim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevSkim.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;language&quot;: [
        ///      &quot;c&quot;,
        ///      &quot;cpp&quot;,
        ///      &quot;csharp&quot;,
        ///      &quot;coffeescript&quot;,
        ///      &quot;fsharp&quot;,
        ///      &quot;go&quot;,
        ///      &quot;groovy&quot;,
        ///      &quot;jade&quot;,
        ///      &quot;objective-C&quot;,
        ///      &quot;rust&quot;,
        ///      &quot;wwift&quot;,
        ///      &quot;javascript&quot;,
        ///      &quot;java&quot;,
        ///      &quot;typescript&quot;,
        ///      &quot;php&quot;
        ///    ],    
        ///    &quot;preffix&quot;: &quot;//&quot;,
        ///    &quot;suffix&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;language&quot;: [
        ///      &quot;perl&quot;,
        ///      &quot;perl6&quot;,
        ///      &quot;r&quot;,
        ///      &quot;shellscript&quot;,
        ///      &quot;ruby&quot;,
        ///      &quot;yaml&quot;,
        ///      &quot;powershell&quot;,      
        ///      &quot;python&quot;
        ///    ],    
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;c&quot;,
        ///        &quot;extensions&quot;: [&quot;c&quot;]    
        ///    },    
        ///    {
        ///        &quot;name&quot;: &quot;cpp&quot;,
        ///        &quot;extensions&quot;: [&quot;cpp&quot;, &quot;h&quot;]    
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;csharp&quot;,
        ///        &quot;extensions&quot;: [&quot;cs&quot;]    
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;vb&quot;,
        ///        &quot;extensions&quot;: [&quot;vb&quot;]    
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;python&quot;,
        ///        &quot;extensions&quot;: [&quot;py&quot;]    
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;javascript&quot;,
        ///        &quot;extensions&quot;: [&quot;js&quot;]    
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;javascriptreact&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
    }
}
