#!/bin/sh
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# Symlink bin command to /usr/bin
rm -f /usr/bin/devskim
ln -s /usr/share/devskim/bin/devskim /usr/bin/devskim

