//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DevSkim.VisualStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DevSkim.VisualStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim.
        /// </summary>
        internal static string _1000 {
            get {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim Rule Options.
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim options for rules.
        /// </summary>
        internal static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressions.
        /// </summary>
        internal static string _1004 {
            get {
                return ResourceManager.GetString("1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim Suppression Options.
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim options for suppressions.
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance.
        /// </summary>
        internal static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim Guidance Options.
        /// </summary>
        internal static string _1008 {
            get {
                return ResourceManager.GetString("1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim options for guidance.
        /// </summary>
        internal static string _1009 {
            get {
                return ResourceManager.GetString("1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignores.
        /// </summary>
        internal static string _1010 {
            get {
                return ResourceManager.GetString("1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim Ignore Options.
        /// </summary>
        internal static string _1011 {
            get {
                return ResourceManager.GetString("1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim options for ignores.
        /// </summary>
        internal static string _1012 {
            get {
                return ResourceManager.GetString("1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findings.
        /// </summary>
        internal static string _1013 {
            get {
                return ResourceManager.GetString("1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim Finding Options.
        /// </summary>
        internal static string _1014 {
            get {
                return ResourceManager.GetString("1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim options for findings.
        /// </summary>
        internal static string _1015 {
            get {
                return ResourceManager.GetString("1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string _1016 {
            get {
                return ResourceManager.GetString("1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim Trigger Options.
        /// </summary>
        internal static string _1017 {
            get {
                return ResourceManager.GetString("1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevSkim options for scan triggers.
        /// </summary>
        internal static string _1018 {
            get {
                return ResourceManager.GetString("1018", resourceCulture);
            }
        }
    }
}
