name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: devskim-results.sarif # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: devskim-results.sarif
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 1 # optional
    - name: Upload DevSkim scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: devskim-results.sarif
