name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1.0.4
      with:
        # The sub directory of the repository root to scan. Repository root used by default.
        directory-to-scan: "GITHUB_WORKSPACE" # optional, default is GITHUB_WORKSPACE
        # Optionally scan the contents of archives.
        should-scan-archives: false # optional
        # The filename for the output.
        output-filename: "devskim-results.sarif" # optional, default is devskim-results.sarif
        # The sub directory for the output under GITHUB_WORKSPACE.
        output-directory: "GITHUB_WORKSPACE" # optional, default is GITHUB_WORKSPACE
        # Optional comma separated list of file globs to ignore when scanning.
        ignore-globs: "**/.git/**,**/bin/**"
